# Generated by Django 5.1.7 on 2025-03-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='author',
        ),
    ]
