# Generated by Django 5.1.7 on 2025-03-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_email_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
