# Generated by Django 5.1.7 on 2025-03-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_is_venue_owner_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
