# Generated by Django 5.1.7 on 2025-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_user_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
