# Generated by Django 5.1.7 on 2025-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.AutoField(primary_key=True, serialize=False)),
                ('venuename', models.CharField(max_length=255)),
                ('venueaddress', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('features', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('imageurl', models.JSONField()),
            ],
        ),
    ]
