# Generated by Django 5.1.7 on 2025-03-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
    ]
