# Generated by Django 5.1.7 on 2025-03-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_venue_options_alter_venue_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='venue',
            table='api_venue',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
            options={
                'unique_together': {('venue', 'start_date', 'end_date')},
            },
        ),
    ]
